### ISSUE TITLE
Is the book still being maintained 

### ISSUE THREAD

**Issue by nasir733** [feldroy/two-scoops-of-django-3.x#240]
there are some sections that are still not done and it has been more than a year since I purchased the book. if there have been updates the book so from where can I get the updated version

**Comment by arielaco** [comment]
Wondering the same here. As time goes on it becomes more and more outdated. I've also come across multiple dead links that I can't check against web archive since they use a link shortener.

I'm fully aware this was marketed as an alpha but I still feel somewhat disappointed due to the lack of communication and progress.

If there are any other books out there similarly useful, I'd love to hear about them.

**Comment by pydanny** [comment]
Sorry, between parenthood, extended family emergencies, career, injuries, and more, time got away from us.

You'll also notice:

- Our open source contributions have gone to nearly zero
- Our community involvement is minimal 

I wish I had a better answer.

**Comment by onno-timmerman** [comment]
@pydanny 
any update on this for 2024 ... or 2025 😃 
would love to see HTMX chapter

**Comment by pydanny** [comment]
Apologies, we sent out the final update in August. @onno-timmerman it will have gone to the email for you that I see is in our system.
