### ISSUE TITLE
Style issue on "bad" code blocks

### ISSUE THREAD

**Issue by deeprave** [feldroy/two-scoops-of-django-3.x#38]
## Location within the Book

Any block with a "bad code" example, for example: "Example 1.2: Bad Python Imports". All of the comment text is invisible when viewed on some reading devices.

## Description 

These blocks are completely unreadable on e.g. a Kindle paperwhite device which renders in greyscale so relies on contrast for readability. The "grey" text is not visible at all, and dark red text is almost invisible.

## Possible Solutions

Please provide a light background, always. Light red if must be, but a dark background and darker white foreground make the example code unreadable due to lack of contrast.

PS: A .mobi and/or .epub release of this book would be greatly appreciated. The PDF version converted to these formats does not allow native font change, text resizing and page reflow which very much sucks for reading ebooks on almost any device.

**Comment by pydanny** [comment]
We'll try to get a light background working ASAP. 

As for .mobi and .epub, honestly that probably won't happen for at least 30 days. Our customized LaTeX doesn't play nice with `TextHT` and we have to write a new custom formatter to reflect on changes in the LaTeX universe since 2017. For now we are focusing on getting the material in the book in better edited shape before we dive into a major formatting effort.

**Comment by pydanny** [comment]
Resolved weeks ago! 😄
